### ISSUE TITLE
Chrome browser becomes unresponsive

### ISSUE THREAD

**Issue by vasilischatziathanasiou** [AuthEceSoftEng/web-recorder-chrome-plugin#3]
Hi,

there seems to be an issue with the plugin and the chrome process. When starting the recorder and after the first initial inputs the chrome process fires out to 100%CPU and after awhile browser becomes completely unresponsive.

It seems not related to chrome version since the problem occurs in both the windows (Version 59.0.3071 (64-bit)) and linux (Version 55.0.2883.75 (64-bit))

**Comment by dimitrisniras** [comment]
Hi @vasilischatziathanasiou ,

In Single Page Apps like Cassandra, due to the difficulty of recording actions, there are many processes that runs in background simultaneously in order to recorder every step. This phenomenon does not been observed in classic sites. 

One solution to this is to create small tests and add them later as pre-conditions to other tests. 

I couldn't find solution to this extension problem, but i will try to fix it.

**Comment by dimitrisniras** [comment]
Hi @vasilischatziathanasiou ,

Problem with chrome process  has solved.

Thanks for reporting.

**Comment by kyrcha** [comment]
@vasilischatziathanasiou @dimitrisniras Just for future notice: because the software and the issues will be public try to keep the converation as general as possible. For example don't mention Cassandra or put the urls of specific apps. I will edit the issues later on. Thank you.
