### ISSUE TITLE
 Error: ELEMENT CANNOT BE ASSIGNED

### ISSUE THREAD

**Issue by vasilischatziathanasiou** [AuthEceSoftEng/web-recorder-chrome-plugin#4]
After installing the new plugin version the test case fails at sign-in when trying to assign user name into the relevant input field.
Checking the steps i see that both the XPath and the URL are correctly retrieved in the step. 
However, the element cannot be assigned with the string value.

Additional Comments/Notes: 
1) I was forced to clean all browser cookies because it was not possible to assign a different user name than the ones already saved.
2) Perhaps it would be better before each test to apply:
browser.driver.manage().deleteAllCookies(); 
so that the user does not have to clean all the cookies before running a test.

@dimitrisniras can you check if you can reproduce the same fault? It is a simple sign in in the eQuad app.

**Comment by dimitrisniras** [comment]
The application should now work perfectly. The problem was on okeanos server. 

Regarding cookies I don't think that you have to clean them before a test case running. Selenium is running on server side and opens an incognito window every time you run a test so it has not save any credential.

Also for recording the only thing that you have to do in Sign In if you have saved your credentials is to click Sign In button and the input fields automatically will be recorded. If you want to type a new user name or password, the fields will change with the new values.
